#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
logo_white = "images/logo-white.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "160px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Simplify VMS"
# purgeCSS
purge_css = true
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
#footer content
footer_content = "Lorem ipsum dolor sit sed dmi amet consectetur adipiscing. Cdo tellussed condimentum volutpat."
# copyright
copyright = "Copyright 2023 Simplify VMS"

# Navigation button
[navigation_button]
enable = true
label = "Start journey"
link = "demo/"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = []
description = ""
author = "Simplify VMS"
image = "images/og-image.png" # this image will be used as fallback if a page has no image of its own

# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "recent-post", "tags"]
# available widget : search,categories,tags,recent-post

############################# social site ########################
[[social]]
title = "facebook"
icon = "fa-brands fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "twitter"
icon = "fa-brands fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "instagram"
icon = "fa-brands fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "viber"
icon = "fa-brands fa-viber" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
